export * from './userActions'

export const ActionTypes = {
  /**
   * user actions
   */
  SET_DEGREE_PROGRAMS: 'SET_DEGREE_PROGRAMS',

  ADD_COURSE_TO_PLAN: 'ADD_COURSE_TO_PLAN',
  CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',

  ADD_ACADEMIC_UNIT: 'ADD_ACADEMIC_UNIT',

  SET_UNPLANNED_COURSES: 'SET_UNPLANNED_COURSES',
  SET_ACADEMIC_UNITS: 'SET_ACADEMIC_UNITS'
}
